CREATE TABLE IF NOT EXISTS BRAND (
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    VERSION    INT       NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    DELETED    BOOLEAN   NOT NULL DEFAULT FALSE,

    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEVICE (

    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    VERSION    INT       NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    DELETED    BOOLEAN   NOT NULL DEFAULT FALSE,

    DEVICE_NAME VARCHAR(100) NOT NULL,
    BRAND_ID VARCHAR(36) NOT NULL REFERENCES BRAND (ID)
);