INSERT INTO BRAND (ID, VERSION, CREATED_AT, UPDATED_AT, DELETED, NAME)
VALUES (gen_random_uuid(), 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 'Samsung');

INSERT INTO BRAND (ID, VERSION, CREATED_AT, UPDATED_AT, DELETED, NAME)
VALUES (gen_random_uuid(), 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 'APPLE');

INSERT INTO BRAND (ID, VERSION, CREATED_AT, UPDATED_AT, DELETED, NAME)
VALUES (gen_random_uuid(), 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 'DELL');



